.TH 1
.SH sisa16_emu
Customized Emulator for the sisa16 virtual portable computer architecture.
.SH SYNOPSIS
.B sisa16_emu
.IR filename
.I Additional_arguments_if_you_want_a_memory_dump
.SH DESCRIPTION
.B sisa16_emu
loads an address space image into memory and executes it in the SISA16 virtual machine
.SH OPTIONS
if you add extra arguments, you get a memory dump at the end of execution.
.SH AUTHOR
David MHS Webster, 2021
.SH LICENSE
See the CC0 License.
