.TH 1
.SH sisa16
Customized Emulator for the sisa16 virtual portable computer architecture.
.SH SYNOPSIS
.B sisa16
.IR filename
.IR segment_size(pages)
.SH DESCRIPTION
.B sisa16
loads an address space image into memory and executes it in the SISA16 virtual machine
.SH OPTIONS
You can specify a number of pages to use in the segment during execution. The default is 1.
.SH AUTHOR
David MHS Webster, 2021
.SH LICENSE
See the CC0 License.
