.TH 1
.SH sisa16_dbg
Customized Debugger for the sisa16 virtual portable computer architecture.
.SH SYNOPSIS
.B sisa16_dbg
.IR filename
.I Additional_arguments_if_you_want_a_memory_dump
.SH DESCRIPTION
.B sisa16_dbg
loads an address space image into memory and executes it in the SISA16 virtual machine, 
but allows you to debug the program as it executes.
.SH OPTIONS
if you add extra arguments, you get a memory dump at the end of execution.
.SH DEBUGGER COMMANDS

When you open the debugger, you will be given a REPL.

Commands are not yet written so I cant tell you what they are, because I havent written them yet!

.SH AUTHOR
David MHS Webster, 2021
.SH LICENSE
See the CC0 License.
