.TH 1
.SH sisa16
Customized Emulator for the sisa16 virtual portable computer architecture.
.SH SYNOPSIS
.B sisa16
.IR filename
[\fBadditional arguments if you want a memory dump\fR]
.SH DESCRIPTION
.B sisa16
loads an address space image into memory and executes it in the SISA16 virtual machine
.SH OPTIONS
if you want a memory dump at the end of execution, pass an additional argument to SISA16 other than filename.
.SH AUTHOR
David MHS Webster, May 19, 2021
.SH LICENSE
See the CC0 License.
