name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
    - name: build_the_demos
      run: make -B asm_programs OPTLEVEL=-Og && ./sisa16_asm -dis clock.bin 0x10000 && ./sisa16_asm -dis clock.bin 0x20000 && ./sisa16_asm -dis echo2.bin 0x20000
    - name: show_environment_info
      run: uname -a && cat /proc/cpuinfo && uname -r && lsb_release -a && gcc --version
