name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    
    timeout-minutes: 5
    
    steps:
    - uses: actions/checkout@v2
    - name: build_the_demos
      run: make -B asm_programs OPTLEVEL=-Og
    - name: show_environment_info
      run: uname -a && cat /proc/cpuinfo && uname -r && lsb_release -a && gcc --version
